name: Send ordre emails med vores email api

on:
  schedule:
    - cron: "0 5 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  send-emails:
    runs-on: ubuntu-latest
    steps:
    - name: Send ordre emails
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://leanders.dk/api/mail'
        method: 'GET'
        timeout: 30000
